name: Build and Push API Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push API Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/api-image:latest ./api
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/api-image:latest
